import { NextRequest, NextResponse } from "next/server";
import JSZip from "jszip";
import { PDFDocument, StandardFonts, rgb, type PDFFont, type PDFPage } from "pdf-lib";
import { createAdminClient } from "@/lib/supabase/admin";
import { getProfile } from "@/lib/auth/profile";

type Exp = {
  vendor: string | null; memo: string | null; amount: number | string | null;
  category: string | null; bc_category: string | null; gl: string | null;
  doc_url: string | null; txn_date: string | null; extracted: { payee?: string } | null;
};
type Trip = { id: string; ent: string | null; dest: string | null; dates: string | null; purpose: string | null };

const NAVY = rgb(0.05, 0.09, 0.16);
const GREEN = rgb(0.13, 0.55, 0.33);
const GRAY = rgb(0.42, 0.46, 0.52);
const RED = rgb(0.78, 0.22, 0.22);

function clip(font: PDFFont, text: string, size: number, maxW: number): string {
  let t = String(text ?? "");
  while (t.length > 1 && font.widthOfTextAtSize(t, size) > maxW) t = t.slice(0, -2);
  return t === String(text ?? "") ? t : t.replace(/.$/, "…");
}
function cell(page: PDFPage, text: string, x: number, y: number, size: number, font: PDFFont, color = NAVY, rightX?: number) {
  const t = String(text ?? "");
  if (rightX != null) page.drawText(t, { x: rightX - font.widthOfTextAtSize(t, size), y, size, font, color });
  else page.drawText(t, { x, y, size, font, color });
}

/** The branded BCX expense report as a PDF (mirrors the on-screen report). */
async function buildReportPdf(trip: Trip, exps: Exp[], tripVendor: string): Promise<Uint8Array> {
  const doc = await PDFDocument.create();
  const font = await doc.embedFont(StandardFonts.Helvetica);
  const bold = await doc.embedFont(StandardFonts.HelveticaBold);
  const M = 50, RIGHT = 612 - M, W = RIGHT - M;
  let page = doc.addPage([612, 792]);
  let y = 792 - M;

  page.drawRectangle({ x: M, y: y - 2, width: W, height: 6, color: NAVY });
  page.drawRectangle({ x: M, y: y - 9, width: W, height: 3, color: GREEN });
  y -= 42;
  cell(page, `BCX expense report — ${trip.dest ?? ""}`, M, y, 18, bold, NAVY);
  y -= 30;

  const meta: [string, string][] = [
    ["TRAVELER", "Jacob Wolbach"], ["ENTITY", trip.ent || "Builders Capital"],
    ["DESTINATION", trip.dest || ""], ["DATES", trip.dates || ""],
  ];
  let mx = M;
  for (const [k, v] of meta) {
    cell(page, k, mx, y, 7, bold, GRAY);
    cell(page, clip(font, v, 10, 120), mx, y - 13, 10, font, NAVY);
    mx += 130;
  }
  y -= 36;
  if (trip.purpose) {
    cell(page, "PURPOSE", M, y, 7, bold, GRAY);
    cell(page, clip(font, trip.purpose, 10, W), M, y - 13, 10, font, NAVY);
    y -= 32;
  }

  // table header
  const cVendor = M + 90, cCat = M + 255, cDoc = M + 410;
  page.drawLine({ start: { x: M, y: y + 6 }, end: { x: RIGHT, y: y + 6 }, thickness: 1, color: NAVY });
  cell(page, "DATE", M, y - 6, 7, bold, GREEN);
  cell(page, "VENDOR", cVendor, y - 6, 7, bold, GREEN);
  cell(page, "BCX CATEGORY", cCat, y - 6, 7, bold, GREEN);
  cell(page, "DOC", cDoc, y - 6, 7, bold, GREEN);
  cell(page, "AMOUNT", 0, y - 6, 7, bold, GREEN, RIGHT);
  y -= 24;

  let total = 0;
  for (const e of exps) {
    if (y < 90) { page = doc.addPage([612, 792]); y = 792 - M; }
    const merchant = e.extracted?.payee || e.memo || e.vendor || "";
    const cat = e.bc_category || e.category || e.gl || "";
    const amt = Number(e.amount || 0); total += amt;
    cell(page, clip(font, String(e.txn_date || trip.dates || ""), 9, 85), M, y, 9, font);
    cell(page, clip(font, merchant, 9, cCat - cVendor - 8), cVendor, y, 9, font);
    cell(page, clip(font, cat, 9, cDoc - cCat - 8), cCat, y, 9, font);
    cell(page, e.doc_url ? "receipt" : "MISSING", cDoc, y, 9, font, e.doc_url ? GREEN : RED);
    cell(page, `$${amt.toFixed(2)}`, 0, y, 9, font, NAVY, RIGHT);
    y -= 18;
  }

  page.drawLine({ start: { x: M, y: y + 8 }, end: { x: RIGHT, y: y + 8 }, thickness: 1, color: NAVY });
  cell(page, "Total", cCat, y - 6, 10, bold);
  cell(page, `$${total.toFixed(2)}`, 0, y - 6, 10, bold, NAVY, RIGHT);
  y -= 36;
  cell(page, clip(font, `Generated by the Builders Capital agent system · receipts in this .zip · one QuickBooks vendor: ${tripVendor}`, 7, W), M, y, 7, font, GRAY);
  return doc.save();
}

/**
 * Trip expense-report .zip: a manifest CSV + every receipt PDF on the trip, bundled for
 * reimbursement / records. Receipts are fetched from their Dropbox share links. Replaces
 * the old toast-only stub on the Travel report.
 *
 * GET /api/travel/export-zip?trip=<id>
 */
export const runtime = "nodejs";
export const maxDuration = 60;

function csvCell(v: unknown): string {
  const s = String(v ?? "");
  return /[",\n]/.test(s) ? `"${s.replace(/"/g, '""')}"` : s;
}

// A Dropbox share link returns an HTML preview unless forced to download — `?dl=1`.
function forceDownload(url: string): string {
  if (/[?&]dl=1/.test(url)) return url;
  if (/[?&]dl=0/.test(url)) return url.replace(/dl=0/, "dl=1");
  return url + (url.includes("?") ? "&dl=1" : "?dl=1");
}

function safe(s: string): string {
  return (s || "").replace(/[^\w.\-]+/g, "_").slice(0, 80);
}

export async function POST(req: NextRequest) {
  const profile = await getProfile();
  if (!profile) return NextResponse.json({ error: "unauthorized" }, { status: 401 });
  if (!process.env.SUPABASE_SERVICE_ROLE_KEY) {
    return NextResponse.json({ error: "Server not configured: SUPABASE_SERVICE_ROLE_KEY missing" }, { status: 500 });
  }
  const tripId = new URL(req.url).searchParams.get("trip")?.trim();
  if (!tripId) return NextResponse.json({ error: "trip id required" }, { status: 400 });

  const admin = createAdminClient();
  const { data: trip } = await admin
    .from("trips")
    .select("id, ent, dest, dates, purpose")
    .eq("id", tripId)
    .maybeSingle();
  if (!trip) return NextResponse.json({ error: "trip not found" }, { status: 404 });

  const { data: rows } = await admin
    .from("payables_queue")
    .select("vendor, memo, amount, category, bc_category, gl, doc_url, txn_date, extracted")
    .eq("trip_id", tripId)
    .order("txn_date");
  const exps = rows ?? [];

  const zip = new JSZip();
  const tripVendor = exps[0]?.vendor ?? `Trip ${trip.dest}`;

  // 1) manifest CSV
  const header = ["Date", "Merchant", "Category", "Amount", "Receipt", "QB Vendor"];
  const lines = [header.map(csvCell).join(",")];
  for (const e of exps) {
    const merchant = (e.extracted as { payee?: string } | null)?.payee || e.memo || e.vendor;
    const cat = e.bc_category || e.category || e.gl || "";
    lines.push([e.txn_date || trip.dates, merchant, cat, e.amount, e.doc_url ? "yes" : "MISSING", tripVendor].map(csvCell).join(","));
  }
  zip.file("expense-summary.csv", lines.join("\n"));

  // 2) the branded BCX expense report as a PDF (the on-screen report, for records)
  try {
    const pdf = await buildReportPdf(trip as Trip, exps as Exp[], tripVendor);
    zip.file(`${safe(trip.dest || "trip")}_expense_report.pdf`, pdf);
  } catch (err) {
    console.error("[export-zip] report PDF failed:", err);
  }

  // 3) the receipt PDFs
  const receipts = zip.folder("receipts")!;
  let attached = 0;
  let missing = 0;
  for (const e of exps) {
    if (!e.doc_url) { missing += 1; continue; }
    try {
      const res = await fetch(forceDownload(e.doc_url));
      if (!res.ok) { missing += 1; continue; }
      const buf = Buffer.from(await res.arrayBuffer());
      const merchant = (e.extracted as { payee?: string } | null)?.payee || e.vendor;
      receipts.file(`${safe(String(e.txn_date || ""))}_${safe(merchant)}_${e.amount}.pdf`, buf);
      attached += 1;
    } catch {
      missing += 1;
    }
  }

  const blob = await zip.generateAsync({ type: "nodebuffer" });
  const fname = `${safe(trip.dest)}_expense_report.zip`;
  return new NextResponse(new Uint8Array(blob), {
    status: 200,
    headers: {
      "Content-Type": "application/zip",
      "Content-Disposition": `attachment; filename="${fname}"`,
      "X-Receipts-Attached": String(attached),
      "X-Receipts-Missing": String(missing),
    },
  });
}
